=== HandsomeChau/winter2015-lab06/data/bonanza.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT __ROOT__ ANY>
<!ATTLIST __ROOT__ version CDATA #REQUIRED>

<!-- Order -->
<!ELEMENT order (customer, delivery?, burger+, special?)>

<!-- Customer -->
<!ELEMENT customer (#PCDATA)>

<!--  -->
<!ATTLIST order type (eatin|takeout|delivery) #REQUIRED>

<!-- Delivery -->
<!ELEMENT delivery (#PCDATA)>

<!ELEMENT special (#PCDATA)>

<!ELEMENT burger (patty, cheeses?, topping*, sauce*, instructions?, name?)>

<!ELEMENT patty (#PCDATA)>
<!ATTLIST patty type (beef|pork|turkey|bison|vege) "beef">

<!ELEMENT cheeses EMPTY>
<!ATTLIST cheeses
        top (american|swiss|jack|blue|gruyere|gouda|aged|goat|brie) #IMPLIED
        bottom (american|swiss|jack|blue|gruyere|gouda|aged|goat|brie) #IMPLIED
>

<!ELEMENT topping (#PCDATA)>
<!ATTLIST topping
        type (lettuce|tomato|raw|dill|roasted|shrooms|salsa|bacon|chillies|fkchilli|avocado|egg|porkbelly) #REQUIRED
>

<!ELEMENT sauce EMPTY>
<!ATTLIST sauce type (ketchup|mustard|mayo|fksauce) #REQUIRED>

<!ELEMENT instructions (#PCDATA)>

<!ELEMENT name (#PCDATA)>

=== HandsomeChau/winter2015-lab06/data/my-order.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE order SYSTEM 'bonanza.dtd'>
<order type="takeout">
    <customer>Edwin</customer>
    <burger>
        <patty type="beef"/>
        <cheeses top="goat" bottom="jack"/>
        <topping type="bacon"/>
        <topping type="egg"/>
        <topping type="shrooms"/>
        <sauce type="mayo"/>
        <sauce type="fksauce"/>
    </burger>
</order>
